# Replace 172.31.18.232 with your sampler instance's actual private IP
prdcr_add name=vpic_sampler xprt=sock host=172.31.18.232 port=10444 type=active reconnect=10s
prdcr_start name=vpic_sampler

updtr_add name=all_sets interval=1s offset=100ms
updtr_prdcr_add name=all_sets regex=.*
updtr_start name=all_sets
